# Generated by Django 2.1.1 on 2018-10-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип дистрибьютора', verbose_name='Тип')),
                ('distr', models.CharField(help_text='Наименование дистрибьютора', max_length=200, verbose_name='Дистрибьютор')),
                ('alias', models.CharField(blank=True, help_text='Псевдоним используется для официальных названий или указания головы', max_length=200, verbose_name='Псевдоним')),
                ('url', models.URLField(blank=True, help_text='Ссылка на сайт дистрибьютора', max_length=300, verbose_name='Ссылка')),
                ('img', models.ImageField(help_text='Логотип дистрибьютора (Желательно SVG)', upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
            },
        ),
    ]
