# Generated by Django 2.1.1 on 2018-10-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип', verbose_name='Тип')),
                ('code', models.CharField(help_text='Код дистрибьютора', max_length=200, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Код дистрибьютора',
            },
        ),
        migrations.AlterField(
            model_name='distr',
            name='img',
            field=models.ImageField(help_text='Логотип дистрибьютора (Желательно SVG)', upload_to='', verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='code',
            name='distr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор'),
        ),
        migrations.AddField(
            model_name='code',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт'),
        ),
    ]
