# Generated by Django 2.1.1 on 2018-10-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product'),
        ('parsing', '0003_auto_20181004_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип', verbose_name='Тип')),
                ('code', models.CharField(help_text='Код дистрибьютора', max_length=200, verbose_name='Код')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Код дистрибьютора',
            },
        ),
    ]
