# Generated by Django 2.1.1 on 2018-10-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип', verbose_name='Тип')),
                ('code', models.CharField(help_text='Исключаемый код дистрибьютора', max_length=200, verbose_name='Код')),
                ('description', models.TextField(blank=True, help_text='Описние', null=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, null=True, verbose_name='Комментарий')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Исключённый код',
            },
        ),
    ]
