# Generated by Django 2.1.1 on 2018-10-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_exceptcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Анулирован'), (1, 'Обработан'), (2, 'В обработке')], db_index=True, default=2, help_text='Тип', verbose_name='Тип')),
                ('date', models.DateTimeField(blank=True, help_text='Дата прайса', null=True, verbose_name='Дата')),
                ('count', models.IntegerField(blank=True, help_text='Количество позиций', null=True, verbose_name='Позиции')),
                ('count_new', models.IntegerField(blank=True, help_text='Количество новых позиций', null=True, verbose_name='Новые позиции')),
                ('file', models.FileField(help_text='Файл с прайсом', upload_to='price', verbose_name='Файл')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
    ]
