# Generated by Django 2.1.1 on 2018-11-01 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0006_distrfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrfile',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 16, 15, 1, 747858, tzinfo=utc), help_text='Дата прайса', null=True, verbose_name='Дата'),
        ),
    ]
