# Generated by Django 2.1.1 on 2018-11-02 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product'),
        ('parsing', '0007_auto_20181101_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Неактивна'), (1, 'Активная'), (2, 'Заблокированна')], db_index=True, default=2, help_text='Тип', verbose_name='Тип')),
                ('name', models.CharField(help_text='Наименование категории дистрибьютора', max_length=300, verbose_name='Категрия')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Категория дистрибьютора',
                'verbose_name_plural': 'Категории дистрибьютора',
            },
        ),
        migrations.AlterField(
            model_name='distrfile',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата прайса', null=True, verbose_name='Дата'),
        ),
    ]
