# Generated by Django 2.1.1 on 2018-11-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_auto_20181102_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrcategory',
            name='category',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Категория'),
        ),
    ]
