# Generated by Django 2.1.1 on 2018-11-02 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product'),
        ('parsing', '0010_auto_20181102_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='distrcategory',
            name='category',
            field=models.ForeignKey(default=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория'),
        ),
    ]
