# Generated by Django 2.1.1 on 2018-11-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0014_auto_20181104_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена'),
        ),
    ]
