# Generated by Django 2.1.1 on 2018-11-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0015_auto_20181104_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='code',
        ),
        migrations.RemoveField(
            model_name='price',
            name='distr',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
