# Generated by Django 2.1.1 on 2018-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0017_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrfile',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Анулирован'), (1, 'Обработан'), (2, 'В обработке'), (3, 'Ожидает')], db_index=True, default=2, help_text='Тип', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Устарела'), (1, 'Актуальная')], db_index=True, default=1, help_text='Тип', verbose_name='Тип'),
        ),
    ]
