# Generated by Django 2.1.1 on 2018-11-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20181111_0730'),
        ('parsing', '0018_auto_20181108_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Устарели'), (1, 'Актуальны')], db_index=True, default=1, help_text='Тип', verbose_name='Тип')),
                ('var', models.SmallIntegerField(choices=[(0, ''), (1, '<'), (2, '>')], default=0, help_text='Больще/меньше', verbose_name='Примерно')),
                ('value', models.IntegerField(blank=True, help_text='Остатки на складе', null=True, verbose_name='Объёмы')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Code', verbose_name='Код дистрибьютора')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Остатки',
                'verbose_name_plural': 'Остатки',
            },
        ),
    ]
