# Generated by Django 2.1.1 on 2018-11-18 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20181118_0943'),
        ('parsing', '0019_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Неактивна'), (1, 'Активная'), (2, 'Заблокированна'), (3, 'Новая')], db_index=True, default=2, help_text='Тип', verbose_name='Тип')),
                ('name', models.CharField(help_text='Наименование категории дистрибьютора', max_length=300, verbose_name='Категрия')),
                ('category', models.ForeignKey(default=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
            },
        ),
        migrations.AlterModelOptions(
            name='exceptcode',
            options={'permissions': (('except_code', 'Исключать код'),), 'verbose_name': 'Исключённый код', 'verbose_name_plural': 'Исключённые коды'},
        ),
    ]
