# Generated by Django 2.1.1 on 2018-11-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0022_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.SmallIntegerField(choices=[(0, 'Неизвестно'), (1, 'USD')], db_index=True, default=1, help_text='Банковский символ валюты', verbose_name='Валюта')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Котировка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('distr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.Distr', verbose_name='Дистрибьютор')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
            },
        ),
    ]
