# Generated by Django 2.1.3 on 2019-01-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0019_auto_20181118_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Set', verbose_name='Сборка')),
            ],
            options={
                'verbose_name': 'Компоненты сборки',
                'verbose_name_plural': 'Компоненты сборок',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип сборки',
                'verbose_name_plural': 'Типы сборки',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='set',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.SetType', verbose_name='Тип'),
        ),
    ]
