# Generated by Django 2.1.3 on 2019-01-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Анулированно'), (1, 'Активно'), (2, 'Архив')], db_index=True, default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Набор пользователя',
                'verbose_name_plural': 'Наборы пользователей',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.SetType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='setuser',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Set', verbose_name='Сборка'),
        ),
        migrations.AddField(
            model_name='setuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Продукт'),
        ),
    ]
