# Generated by Django 2.1.3 on 2019-01-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20190128_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='type',
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setuser',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='SetList',
        ),
        migrations.DeleteModel(
            name='SetType',
        ),
        migrations.DeleteModel(
            name='SetUser',
        ),
    ]
