# Generated by Django 2.1.3 on 2019-01-28 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_auto_20181118_0943'),
        ('calculate', '0003_auto_20190129_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Активный набор',
                'verbose_name_plural': 'Активные наборы',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Ноборы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Set', verbose_name='Сборка')),
            ],
            options={
                'verbose_name': 'Компоненты сборки',
                'verbose_name_plural': 'Компоненты сборок',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, null=True, verbose_name='Комментарий')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Set', verbose_name='Сборка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Набор пользователя',
                'verbose_name_plural': 'Ноборы  пользователей',
                'ordering': ('id',),
            },
        ),
    ]
