# Generated by Django 2.1.3 on 2019-01-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_activset_set_setlist_setuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activset',
            name='product',
        ),
        migrations.RemoveField(
            model_name='activset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='setlist',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setuser',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivSet',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='SetList',
        ),
        migrations.DeleteModel(
            name='SetUser',
        ),
    ]
