# Generated by Django 2.1.3 on 2019-01-28 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0019_auto_20181118_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculate', '0005_auto_20190129_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, help_text='Объём закупаемого товара', verbose_name='Количество')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Активный набор',
                'verbose_name_plural': 'Активные наборы',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Анулирован'), (1, 'Активeн'), (2, 'Закрыт'), (3, 'Выполнен')], db_index=True, default=1, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Ноборы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, help_text='Объём закупаемого товара', verbose_name='Количество')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='Продукт')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Set', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Компоненты набора',
                'verbose_name_plural': 'Компоненты наборов',
            },
        ),
    ]
