# Generated by Django 2.1.1 on 2018-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип категории', verbose_name='Тип')),
                ('name', models.CharField(help_text='Наименование категории', max_length=200, verbose_name='Категория')),
                ('alias', models.CharField(blank=True, help_text='Псевдоним используется для профессионализмов, жаргона, сокращений и т.д. (CPU, RAM, HDD...)', max_length=200, verbose_name='Псевдоним')),
                ('img', models.ImageField(help_text='Картинка соответствующая категории', upload_to='', verbose_name='Картинка')),
            ],
        ),
    ]
