# Generated by Django 2.1.1 on 2018-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(help_text='Заголовок состоит из: Категория Вендор Артикул', max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, help_text='Ссылка на сайте производителя', max_length=500, verbose_name='Ссылка'),
        ),
    ]
