# Generated by Django 2.1.1 on 2018-10-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181001_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Вендор'},
        ),
        migrations.AlterField(
            model_name='product',
            name='alias',
            field=models.TextField(blank=True, help_text='Техническое название с краткими характеристиками', max_length=1000, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описние с подробными характеристиками', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, help_text='Полное название с краткими характеристиками', max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, help_text='Заголовок состоит из: Категория Вендор Артикул', max_length=1000, verbose_name='Заголовок'),
        ),
    ]
