# Generated by Django 2.1.1 on 2018-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181002_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alias',
            field=models.TextField(blank=True, help_text='Техническое название с краткими характеристиками', max_length=1000, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text='Артикул товара', max_length=200, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описние с подробными характеристиками', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iarticle',
            field=models.CharField(blank=True, help_text='Заводской или внутренний артикул', max_length=200, null=True, verbose_name='Артикул Exp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, help_text='Полное название с краткими характеристиками', max_length=1000, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, help_text='Заголовок состоит из: Категория Вендор Артикул', max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, help_text='Ссылка на сайте производителя', max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
