# Generated by Django 2.1.1 on 2018-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181002_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(help_text='Картинка спродукта', null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
