# Generated by Django 2.1.1 on 2018-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181002_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Вендор'),
        ),
    ]
