# Generated by Django 2.1.1 on 2018-10-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181002_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
