# Generated by Django 2.1.1 on 2018-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок состоит из: Категория Вендор Артикул', max_length=300, null=True, verbose_name='Заголовок'),
        ),
    ]
