# Generated by Django 2.1.1 on 2018-10-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20181004_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активно'), (1, 'Активно'), (2, 'Заблокировано')], db_index=True, default=1, help_text='Тип', verbose_name='Тип')),
                ('iarticle', models.CharField(blank=True, help_text='Заводской или внутренний артикул', max_length=200, null=True, verbose_name='Артикул Exp')),
                ('article', models.CharField(blank=True, help_text='Артикул товара', max_length=200, null=True, verbose_name='Артикул')),
                ('title', models.CharField(blank=True, help_text='Заголовок состоит из: Категория Вендор Артикул', max_length=300, null=True, verbose_name='Заголовок')),
                ('name', models.TextField(blank=True, help_text='Полное название с краткими характеристиками', max_length=1000, null=True, verbose_name='Название')),
                ('alias', models.TextField(blank=True, help_text='Техническое название с краткими характеристиками', max_length=1000, null=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, help_text='Описние с подробными характеристиками', null=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, help_text='Комментарии специалистов для внутреннего пользования', max_length=1000, null=True, verbose_name='Комментарий')),
                ('url', models.URLField(blank=True, help_text='Ссылка на сайте производителя', max_length=500, null=True, verbose_name='Ссылка')),
                ('img', models.ImageField(help_text='Картинка спродукта', null=True, upload_to='', verbose_name='Картинка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Продукт',
            },
        ),
    ]
