# Generated by Django 2.1.1 on 2018-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181104_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=0, help_text='Уникальный код товара', verbose_name='Нумерация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iarticle',
            field=models.CharField(blank=True, help_text='Заводской или внутренний артикул', max_length=200, null=True, verbose_name='Артикул тех.'),
        ),
    ]
