# Generated by Django 2.1.3 on 2018-12-02 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Неопределено'), (1, 'Персона'), (2, 'Организация')], db_index=True, default=1, help_text='Тип участника', verbose_name='Тип')),
                ('sex', models.SmallIntegerField(choices=[(0, 'Неопределен'), (1, 'Мужской'), (2, 'Женский')], db_index=True, default=0, help_text='Пол участника', verbose_name='Пол')),
                ('title', models.CharField(help_text='Обрвщене к участнику', max_length=200, verbose_name='Наименование')),
                ('surname', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('registration', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Не активен'), (1, 'Основной'), (2, 'Дополнительный')], db_index=True, default=1, help_text='Тип контакта', verbose_name='Тип')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='ТелеФон')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrm.Member', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
