# Generated by Django 2.1.3 on 2019-01-13 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mrm', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.SmallIntegerField(choices=[(0, 'Сброс'), (1, 'Активна'), (2, 'Заверщена'), (3, 'Выполнена')], db_index=True, default=1, help_text='Режим сессии', verbose_name='Режим')),
                ('ses_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Начало')),
                ('ses_stop', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='ses',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrm.Member', verbose_name='Участник'),
        ),
    ]
